<?php

return [
    'list' => [
        'Nông nghiệp và Phát triển nông thôn (VBA)',
        'Ngoại thương Việt Nam (VCB)',
        'Đầu tư và phát triển (BIDV)',
        'Công Thương Việt Nam (VIETINBANK)',
        'Việt Nam Thịnh Vượng (VPB)',
        'Quốc tế (VIB)',
        'Xuất nhập khẩu (EIB)',
        'Sài Gòn Hà Nội (SHB)',
        'Tiên Phong (TPB)',
        'Kỹ Thương (TCB)',
        'Hàng hải (MSB)',
        'Ngân hàng Thương mại Cổ phần Lộc Phát Việt Nam (LPB)',
        'Đông Á (DAB)',
        'Bắc Á (NASB)',
        'Sài Gòn Công thương (SGB)',
        'Việt Nam Thương tín (VIETBANK)',
        'BVBank – Ngân hàng TMCP Bản Việt (VCCB)',
        'Kiên Long (KLB)',
        'Ngân hàng TMCP Thịnh vượng và Phát triển (PGB)',
        'Đại chúng Việt Nam (PVC)',
        'Á Châu (ACB)',
        'Nam Á (NAMABANK)',
        'Sài Gòn (SCB)',
        'Đông Nam Á (SEAB)',
        'Phương Đông (OCB)',
        'Việt Á (VAB)',
        'Quốc Dân (NCB)',
        'Liên doanh VID Public Bank (VID)',
        'Bảo Việt (BVB)',
        'Ngân hàng TNHH MTV Việt Nam Hiện Đại (MBV)',
        'Phát triển nhà TP HCM (HDB)',
        'Dầu khí toàn cầu (GPB)',
        'Sacombank (STB)',
        'An Bình (ABBANK)',
        'TNHH MTV Hong Leong VN (HLB)',
        'MTV Shinhan Việt Nam (SHBVN)',
        'Liên Doanh Việt Nga (VRB)',
        'Xây dựng Việt Nam (CBB)',
        'United Overseas Bank Việt Nam (UOB)',
        'Woori Việt Nam (Woori)',
        'Indovina (IVB)',
        'Việt Nam Thịnh Vượng CAKE BANK (CAKEVPB)',
        'Việt Nam Thịnh Vượng UBANK (UBANKVPB)',
        'Quân đội (MB)',
    ],
];
