<?php

namespace App\Http\Controllers;

use App\Models\LinkRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class DashboardController extends Controller
{
    public function index(): View
    {
        $user = auth()->user();

        $pinnedLinks = LinkRequest::forUser($user)
            ->pinned()
            ->latest('pinned_at')
            ->limit(5)
            ->get();

        $recentLinks = LinkRequest::forUser($user)
            ->latest()
            ->limit(5)
            ->get();

        $latestResult = LinkRequest::forUser($user)
            ->whereNotNull('affiliate_url')
            ->latest()
            ->first();

        return view('dashboard', compact('pinnedLinks', 'recentLinks', 'latestResult'));
    }

    public function store(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'original_url' => ['required', 'url', 'max:2048'],
        ]);

        $user = auth()->user();

        // TODO: Replace original_url with real affiliate_url generated by Playwright.
        // When Playwright is implemented:
        //   1. Visit original_url to extract product info.
        //   2. Generate real affiliate link via platform's affiliate program.
        //   3. Compute estimated_cashback based on real commission rate.
        //   4. Set status = 'completed' only after affiliate link is confirmed working.
        $fakeCashback = random_int(1000, 50000);

        LinkRequest::create([
            'user_id' => $user->id,
            'original_url' => $validated['original_url'],
            'platform' => $this->detectPlatform($validated['original_url']),
            'affiliate_url' => $validated['original_url'],
            'estimated_cashback' => $fakeCashback,
            'status' => 'completed',
        ]);

        $formatted = number_format($fakeCashback, 0, ',', '.');

        return redirect()->route('dashboard')
            ->with('success', "Link đã sẵn sàng! Bạn có thể nhận hoàn tiền {$formatted}đ khi mua qua link này.");
    }

    public function togglePin(LinkRequest $linkRequest): RedirectResponse
    {
        $user = auth()->user();

        if ($linkRequest->user_id !== $user->id) {
            abort(403);
        }

        if ($linkRequest->is_pinned) {
            $linkRequest->update([
                'is_pinned' => false,
                'pinned_at' => null,
            ]);
        } else {
            $pinnedCount = LinkRequest::forUser($user)->pinned()->count();

            if ($pinnedCount >= 5) {
                return redirect()->route('dashboard')
                    ->with('error', 'Bạn chỉ có thể ghim tối đa 5 link.');
            }

            $linkRequest->update([
                'is_pinned' => true,
                'pinned_at' => now(),
            ]);
        }

        return redirect()->route('dashboard');
    }

    private function detectPlatform(string $url): string
    {
        $url = strtolower($url);

        $platforms = [
            'shopee'  => 'Shopee',
            'lazada'  => 'Lazada',
            'tiktok'  => 'TikTok Shop',
            'tiki'    => 'Tiki',
        ];

        foreach ($platforms as $domain => $name) {
            if (str_contains($url, $domain)) {
                return $name;
            }
        }

        return 'Khác';
    }
}
